version: 0.2

env:
  variables:
      CACHE_CONTROL: "86400"
      S3_BUCKET: "studi-store"
      BUILD_ENV: "production"

phases:
  install:
    commands:
      - npm install -g @angular/cli@11.2.2
    runtime-versions:
      nodejs: 18.10.0
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration=production

  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/studi-store
      - ls -la
      - aws s3 sync . s3://studi-store --delete
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist/studi-store*'
