export const products = [
  {
    id: 1,
    name: 'Ticket to Ride',
    img: [
      'https://cdn1.philibertnet.com/385325-large_default/ticket-to-ride.jpg',
    ],
    description:
      'Les Aventuriers du Rail vous invite à bord d’une aventure ferroviaire dans laquelle vous collectez des wagons pour prendre le contrôle de chemins de fer reliant les différentes villes des États-Unis d’Amérique.',
    price: '44,95',
    ref: 'DOW7201',
    age: 'à partir de 8 ans',
    nbPlayers: '2 à 5 joueur(s)',
    timing: '30mn à 1h',
    video: 'https://www.youtube.com/embed/4JhFhyvGdik',
  },
  {
    id: 2,
    name: 'Ticket to Ride - Europe',
    img: [
      'https://cdn2.philibertnet.com/388908-large_default/ticket-to-ride-europe.jpg',
      'https://cdn3.philibertnet.com/388909-thickbox_default/ticket-to-ride-europe.jpg',
    ],
    description:
      "Des remparts d'Edimbourg aux docks de Constantinople, des ruelles poussiéreuses de Pampelune aux quais gelés de la grande gare de Saint-Pétersbourg, les Aventuriers du Rail Europe vous emmènent à la découverte de l'Europe des années 1900.",
    price: '44,95',
    ref: 'DOW7202',
    age: 'à partir de 8 ans',
    nbPlayers: '2 à 5 joueur(s)',
    timing: '1 à 2h',
    video: null,
  },
  {
    id: 3,
    name: 'Ticket to Ride Rails & Sails',
    img: [
      'https://cdn2.philibertnet.com/360136-large_default/ticket-to-ride-rails-sails.jpg',
      'https://cdn1.philibertnet.com/360137-thickbox_default/ticket-to-ride-rails-sails.jpg',
      'https://cdn1.philibertnet.com/360138-thickbox_default/ticket-to-ride-rails-sails.jpg',
    ],
    description:
      'De Los Angeles à Sydney, de Mourmansk à Dar Es Salaam, Les Aventuriers du Rail – Autour du monde vous emmènent à la découverte du monde entier. Montez à bord et préparez-vous à un voyage inoubliable !',
    price: '69,95',
    ref: 'DOW720026',
    age: 'à partir de 10 ans',
    nbPlayers: '2 à 5 joueur(s)',
    timing: '1 à 2h',
    video: null,
  },
  {
    id: 4,
    name: 'Ticket to Ride - Nordic Countries',
    img: [
      'https://cdn1.philibertnet.com/437333-large_default/ticket-to-ride-nordic-countries.jpg',
      'https://cdn1.philibertnet.com/437334-small_default/ticket-to-ride-nordic-countries.jpg',
    ],
    description:
      "Dans ce volume de la saga Les Aventuriers du Rail, partez à la découverte de la Scandinavie. Les territoires du Danemark, de la Finlande, de la Norvège et de la Suède n'auront plus de secret pour vous.",
    price: '44,95',
    ref: 'DOW7208',
    age: 'à partir de 8 ans',
    nbPlayers: '2 à 3 joueur(s)',
    timing: '30mn à 1h',
    video: null,
  },
  {
    id: 5,
    name: 'Agricola',
    img: [
      'https://cdn1.philibertnet.com/493136-large_default/agricola-vf.jpg',
      'https://cdn3.philibertnet.com/493135-small_default/agricola-vf.jpg',
    ],
    description:
      'Agricola, le jeu de développement agricole ! « L’édition révisée du jeu stratégique de renommée internationale ! »',
    price: '44,90',
    ref: 'FUN-AGRFR01-FR',
    age: 'à partir de 12 ans',
    nbPlayers: '1 à 4 joueur(s)',
    timing: '1 à 2h',
    video: 'https://www.youtube.com/embed/LH-g7fSRHUU',
  },
  {
    id: 6,
    name: 'Agricola - Extension Belgique',
    img: [
      'https://cdn2.philibertnet.com/322017-thickbox_default/agricola-vf-extension-belgique.jpg',
      'https://cdn2.philibertnet.com/322018-large_default/agricola-vf-extension-belgique.jpg',
    ],
    description:
      'Cette extension propose 120 cartes à ajouter au jeu de base, sans pour autant compliquer sa mécanique avec de nouvelles règles.',
    price: '10,50',
    ref: ' AGRI05-FR',
    age: 'à partir de 10 ans',
    nbPlayers: '1 à 4 joueur(s)',
    timing: 'moins de 30mn',
    video: null,
  },
  {
    id: 7,
    name: 'Agricola : Bubulcus',
    img: [
      'https://cdn2.philibertnet.com/493132-large_default/agricola-bubulcus.jpg',
      'https://cdn3.philibertnet.com/493131-large_default/agricola-bubulcus.jpg',
      'https://cdn1.philibertnet.com/493133-large_default/agricola-bubulcus.jpg',
    ],
    description:
      "Agricola : Bubulcus Deck contient 120 cartes de Savoir Faire et d'Améliorations Mineures à utiliser avec l'édition révisée d'Agricola.",
    price: '14,95',
    ref: 'FUN-AGRBFR01-FR',
    age: 'à partir de 12 ans',
    nbPlayers: '1 à 4 joueur(s)',
    timing: 'moins de 30mn',
    video: null,
  },
  {
    id: 8,
    name: '7 Wonders Nouvelle Édition',
    img: [
      'https://cdn2.philibertnet.com/478484-large_default/7-wonders-nouvelle-edition.jpg',
    ],
    description:
      "Dans 7 Wonders Nouvelle Edition, prenez la tête de l'une des sept grandes cités du monde antique et laissez votre empreinte dans l'histoire des civilisations. Cette boîte est la 2ème édition de ce jeu devenu un classique.",
    price: '40,50',
    ref: 'REP7W01FR',
    age: 'à partir de 10 ans',
    nbPlayers: '3 à 7 joueur(s)',
    timing: ' 30mn à 1h ',
    video: 'https://www.youtube.com/embed/sZHSylvYn0s',
  },
  {
    id: 9,
    name: '7 Wonders Nouvelle Edition - Armada',
    img: [
      'https://cdn3.philibertnet.com/481642-large_default/7-wonders-nouvelle-edition-armada.jpg',
      'https://cdn3.philibertnet.com/493313-small_default/7-wonders-nouvelle-edition-armada.jpg',
    ],
    description:
      "7 Wonders Armada est une extension pour 7 Wonders qui vous fera prendre la tête d'une flotte de navires! Retrouverez dans cette nouvelle édition des paquets de cartes débutant et expert afin de découvrir l'extension facilement.",
    price: '27,00',
    ref: 'REP7W04FR',
    age: 'à partir de 10 ans',
    nbPlayers: '3 à 7 joueur(s)',
    timing: ' 30mn à 1h ',
    video: 'https://www.youtube.com/embed/vAi3A6spW5A',
  },
  {
    id: 10,
    name: '7 Wonders Nouvelle Edition - Leaders',
    img: [
      'https://cdn3.philibertnet.com/482524-large_default/7-wonders-nouvelle-edition-leaders.jpg',
      'https://cdn2.philibertnet.com/493308-large_default/7-wonders-nouvelle-edition-leaders.jpg',
    ],
    description:
      'Au cœur de votre ville, des hommes et des femmes exceptionnels inspirent votre peuple et portent votre civilisation à son apogée.',
    price: '22,50',
    ref: 'REP7W02FR',
    age: ' à partir de 10 ans',
    nbPlayers: '3 à 7 joueur(s)',
    timing: '30mn à 1h',
    video: 'https://www.youtube.com/embed/OUzESpQJE2c',
  },
  {
    id: 11,
    name: 'Carcassonne : Big Box 2021',
    img: [
      'https://cdn1.philibertnet.com/522676-large_default/carcassonne-big-box-2021.jpg',
      'https://cdn1.philibertnet.com/522677-large_default/carcassonne-big-box-2021.jpg',
    ],
    description:
      'Carcassonne : Big Box 2021 est le parfait coffret d’initiation pour entrer dans l’univers du plus célèbre des jeux de pose de tuiles.',
    price: '64,90',
    ref: 'HIGCARCBB01FR',
    age: 'à partir de 7 ans',
    nbPlayers: ' 2 à 6 joueur(s)',
    timing: 'moins de 30mn',
    video: 'https://www.youtube.com/embed/hOrD5pxaPM0',
  },
  {
    id: 12,
    name: 'Carcassonne : Extension 10 - Tous en Piste',
    img: [
      'https://cdn1.philibertnet.com/385757-large_default/carcassonne-vf-tous-en-piste.jpg',
      'https://cdn2.philibertnet.com/387155-large_default/carcassonne-vf-tous-en-piste.jpg',
      'https://cdn3.philibertnet.com/387156-large_default/carcassonne-vf-tous-en-piste.jpg',
    ],
    description:
      'Le cirque se déplace d’un lieu à un autre avec sa ménagerie. Sitôt le chapiteau dressé, tous les meeples des environs affluent pour assister au spectacle !',
    price: '15,00',
    ref: 'CARC11N',
    age: 'à partir de 8 ans',
    nbPlayers: ' 2 à 5 joueur(s)',
    timing: '30mn à 1h',
    video: null,
  },
  {
    id: 13,
    name: 'Mascarade',
    img: [
      'https://cdn2.philibertnet.com/324838-large_default/mascarade.jpg',
      'https://cdn2.philibertnet.com/324839-large_default/mascarade.jpg',
    ],
    description:
      'Pour être le plus riche à la fin de la partie, les joueurs utilisent à chaque tour les pouvoirs de différentes cartes Personnages placées face cachée devant eux.',
    price: '17,95',
    ref: 'MASFR01-FR',
    age: 'à partir de 10 ans',
    nbPlayers: '2 à Plus de 10 joueurs',
    timing: '30mn à 1h',
    video: 'https://www.youtube.com/embed/IlhbUSRWbAo?',
  },
  {
    id: 14,
    name: 'Citadelles - Edition Classique',
    img: [
      'https://cdn1.philibertnet.com/361567-large_default/citadelles-edition-classique.jpg',
      'https://cdn2.philibertnet.com/361568-large_default/citadelles-edition-classique.jpg',
      '',
    ],
    description:
      "Bâtissez la plus belle des cités dans Citadelles. Dans ce classique du jeu de société, usez de stratégie, de bluff et de diplomatie et gérer efficacement vos pièces d'or.",
    price: '13,50',
    ref: 'EFESCI01',
    age: 'à partir de 10 ans',
    nbPlayers: '2 à 7 joueur(s)',
    timing: '30mn à 1h',
    video: 'https://www.youtube.com/embed/sFx8O2uK3UY',
  },
  {
    id: 15,
    name: 'Timeline : Classique',
    img: [
      'https://cdn3.philibertnet.com/494296-large_default/timeline-classique.jpg',
      'https://cdn3.philibertnet.com/494297-large_default/timeline-classique.jpg',
      'https://cdn3.philibertnet.com/494298-large_default/timeline-classique.jpg',
      'https://cdn2.philibertnet.com/494299-large_default/timeline-classique.jpg',
    ],
    description:
      'Timeline : Classique propose des cartes aux thèmes variés (événements, découvertes, inventions, musique, etc.). À vous de placer correctement toutes vos cartes sur la ligne de temps !',
    price: '9,00',
    ref: 'TIME03FR',
    age: 'à partir de 8 ans',
    nbPlayers: '2 à 6 joueur(s)',
    timing: 'moins de 30mn',
    video: 'https://www.youtube.com/embed/XUpWbm1xfcw',
  },
  {
    id: 16,
    name: 'Timeline : Histoire de France',
    img: [
      'https://cdn2.philibertnet.com/494308-small_default/timeline-histoire-de-france.jpg',
      'https://cdn2.philibertnet.com/494309-large_default/timeline-histoire-de-france.jpg',
      'https://cdn3.philibertnet.com/494310-large_default/timeline-histoire-de-france.jpg',
      'https://cdn3.philibertnet.com/494311-large_default/timeline-histoire-de-france.jpg',
    ],
    description:
      'Soyez le premier à placer correctement vos cartes dans la Timeline pour gagner la partie ! Confrontez vos connaissances et votre intuition à l’Histoire de France ! Quand a commencé la construction de Notre-Dame de Paris? Quand Louis XIV s’est-il installé à Versailles? Et Astérix le Gaulois, c’était quand déjà?',
    price: '9,00',
    ref: 'TIMECOFR',
    age: 'à partir de 8 ans',
    nbPlayers: '2 à 6 joueur(s)',
    timing: 'moins de 30mn',
    video: 'https://www.youtube.com/embed/XUpWbm1xfcw',
  },
  {
    id: 17,
    name: 'Timeline : Inventions',
    img: [
      'https://cdn1.philibertnet.com/494327-large_default/timeline-inventions.jpg',
      'https://cdn1.philibertnet.com/494327-large_default/timeline-inventions.jpg',
      'https://cdn1.philibertnet.com/494328-large_default/timeline-inventions.jpg',
      'https://cdn2.philibertnet.com/494329-large_default/timeline-inventions.jpg',
    ],
    description:
      'Avec Timeline : Inventions, trouvez quelle innovation a été découverte avant les autres. Culture générale ou bien jeu de déduction, la frise chronologique est à vous !',
    price: '9,00',
    ref: 'TIME01FR',
    age: 'à partir de 8 ans',
    nbPlayers: '2 à 6 joueur(s)',
    timing: 'moins de 30mn',
    video: 'https://www.youtube.com/embed/XUpWbm1xfcw',
  },
  {
    id: 18,
    name: 'Almadi',
    img: [
      'https://cdn3.philibertnet.com/512399-large_default/almadi.jpg',
      'https://cdn2.philibertnet.com/512400-large_default/almadi.jpg',
    ],
    description:
      'Dans Almadi, les joueurs construisent un royaume en disposant des tuiles de paysage pour plaire au sultan Shahryar.',
    price: '27,00',
    ref: 'FUALM',
    age: 'à partir de 10 ans',
    nbPlayers: '2 à 5 joueur(s)',
    timing: ' 30mn à 1h',
    video: 'https://www.youtube.com/embed/AAqkpCxIuEY',
  },
  {
    id: 19,
    name: 'Brazil : Imperial',
    img: [
      'https://cdn1.philibertnet.com/515668-large_default/brazil-imperial.jpg',
      'https://cdn2.philibertnet.com/515669-large_default/brazil-imperial.jpg',
      'https://cdn1.philibertnet.com/519867-large_default/brazil-imperial.jpg',
    ],
    description:
      'Dans Brazil : Imperial, vous devez construire des bâtiments, gérer les ressources, explorer les terres, créer des échanges commerciaux, acquérir le soutien des plus grandes personnalités du pays, et recruter une puissante armée pour protéger vos intérêts contre les États rivaux.',
    price: '49,50',
    ref: 'JDPSMP064',
    age: ' à partir de 14 ans ',
    nbPlayers: '1 à 4 joueur(s)',
    timing: '1 à 2h',
    video: 'https://www.youtube.com/embed/xPoWBaI1RMc',
  },
  {
    id: 20,
    name: 'Sid Meier’s Civilization : Une Aube Nouvelle',
    img: [
      'https://cdn1.philibertnet.com/415105-large_default/sid-meiers-civilization-une-aube-nouvelle.jpg',
      'https://cdn2.philibertnet.com/415106-large_default/sid-meiers-civilization-une-aube-nouvelle.jpg',
    ],
    description:
      'Sid Meier’s Civilization : Une Aube Nouvelle transpose l’un des plus grands succès du jeu vidéo jamais édité en jeu de stratégie sur plateau.',
    price: '44,95',
    ref: 'CND01FR',
    age: ' à partir de 14 ans',
    nbPlayers: '2 à 4 joueur(s)',
    timing: '1 à 2h',
    video: 'https://www.youtube.com/embed/y_CkUKgzdtM',
  },
];
